### ISSUE TITLE
Разработка по промышленным стандартам

### ISSUE THREAD

**Issue by alehinsasha** [cobern1976/FinalTask#5]
- [x] Одна функциональность = одна фича и сценарии проверяющие работу этой фичи/функциональности
- [x] Использование фикстур
- [x] Повторное использование шагов (собственная библиотека шагов)
- [x] Фичи из воздуха
- [x] Детализация фичи

**Comment by alehinsasha** [comment]
**В дополнение к проверке навыка "Повторное использование шагов (собственная библиотека шагов)"**

Для подтверждения этого навыка у вас должно быть:
1. Две фичи проверяющие поступление и продажу товара.
2. В каталоге features каталог в котором вы будете хранить ваши библиотечные фичи.
3. В этом каталоге библиотечных шагов должна быть одна фича с одним универсальным (параметризованным) шагом который будет удалять документы.
4. В фичах поступления и продажи нужно использовать этот библиотечный шаг.

**Comment by cobern1976** [comment]
4... Не совсем понятно, что подразумевается под пунктами фичи из воздуха и детализация шагов .. Ведь та проверка, что я скинул и создана вся по этой технологии или мне просто дополнить шаги тестирования – тестом функционала по продажам ?

**Comment by alehinsasha** [comment]
Я создать issue с флагами создал, но актуализировал. Сейчас актуализирую)

**Comment by cobern1976** [comment]
Разве обработка ОчисткаДокументовПоПроцессу, которая чистит документы Покупки или Продажи в зависимости от параметра (0 или 1) это не фикстура ?

**Comment by alehinsasha** [comment]
Нет, это шаг, который наверное не "чистит" а удаляет документы. А фикстуры - это документы, справочники, записи регистров и т.д. в общем данные инфобазы хранящиеся в макете которые переносятся из макетов в инфобазу (грубо говоря, данные загружаются).

**Comment by cobern1976** [comment]
Читал определение фикстур - понял так - что это действия, которые приводят базу к некоторому требуемому состоянию. Посчитал, что для наших целей - удаление документов, с тем , чтобы потом ввести новый документ и получить в отчетах некоторое зафиксированное значение вполне подходит под определение. А оказалось - требуется загрузка из макета - ок.

**Comment by alehinsasha** [comment]
> Читал определение фикстур - понял так - что это действия, которые приводят базу к некоторому требуемому состоянию.

что-то не так с этим определением, ведь воспроизведение действий пользователя (поведение) приводит базу к требуемому состоянию, которое потом (в секции Тогда) и проверяется. Но это же фича.

В общем, чтобы в холивар не провалиться, предлагаю действительно оставить так

> А оказалось - требуется загрузка из макета - ок.

Хотя я понимаю фикстуры как данные ранее созданные и содержащиеся в макете.

**Comment by cobern1976** [comment]
в фиче отражения процесса продажи реализована фикстура  загрузки документа Покупки перед продажей (вместо ручной забивки)

**Comment by alehinsasha** [comment]
> в фиче отражения процесса продажи реализована фикстура загрузки документа Покупки перед продажей (вместо ручной забивки)

да, есть.

**Comment by alehinsasha** [comment]
с "Повторное использование шагов" нужна помощь?

**Comment by cobern1976** [comment]
Т.е. то что я для очистки документов во всех сценариях и в покупке и в продаже использую параметризованную процедуру "ЕслиПокупкаТоПризнакОчистки" , которая лежит в обработке ОчисткаДокументовПоПроцессу, это не то ?

**Comment by alehinsasha** [comment]
Это, то. Использовать "Повторное использование шагов" вы умеете. Просто вместо

> Т.е. то что я для очистки документов во всех сценариях и в покупке и в продаже использую параметризованную процедуру "ЕслиПокупкаТоПризнакОчистки" , которая лежит в обработке ОчисткаДокументовПоПроцессу.feature, это не то ?

я ожидал

[ссылку](https://github.com/cobern1976/FinalTask/blob/master/features/%D0%9E%D1%87%D0%B8%D1%81%D1%82%D0%BA%D0%B0%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2%D0%9F%D0%BE%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D1%83.feature#L10) на результат работы)

**Comment by alehinsasha** [comment]
готово
