### ISSUE TITLE
Программная работа с функциональностью "Автоматизированное тестирование 1С"

### ISSUE THREAD

**Issue by alehinsasha** [cobern1976/FinalTask#6]
- [x] Создать свой шаг проверяющий текст сообщения пользователю

**Comment by alehinsasha** [comment]
**В дополнение к проверке навыка "Создать свой шаг проверяющий текст предупреждения"**

Нужно реализовать свой шаг используя функциональность "Автоматизированное тестирование 1С" и свойство "ТестовоПриложение" переменной "КонтекстСохраняемый", который проверяет сообщения пользователю в момент проведения документа реализации товара. Например, если нет в сообщении текста "Не хватает товара" то реализация провелясь корректно. Или если есть текст "Не хватает товара" а товара действительно нет на остатках, то - Ок, функциональность контроля остатков проверена.

**Comment by cobern1976** [comment]
2 сценарий в отражении процесса продажи реализует данный функционал

**Comment by alehinsasha** [comment]
> 2 сценарий в отражении процесса продажи реализует данный функционал

по моему - нет. Покажите (дайте ссылку) на код в которым вы программно работаете с автоматизированным тестированием 1С.

**Comment by cobern1976** [comment]
РаботаССообщниями.epf   процедура - "ПровожуДокументПродажа()"

**Comment by alehinsasha** [comment]
Дайте уже ссылку...

**Comment by alehinsasha** [comment]
https://github.com/cobern1976/FinalTask/blob/1f9ad5ce08f36bfe9721e6a50b032c288221377f/src/features/step_definitions/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%A1%D0%A1%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F%D0%BC%D0%B8/Form/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0.bsl#L74

**Comment by alehinsasha** [comment]
готово
