### ISSUE TITLE
Демонстрация работ заказчику

### ISSUE THREAD

**Issue by alehinsasha** [cobern1976/FinalTask#7]
**Что нужно сделать**
1. Выгрузить конфигурацию в файлы (конфигуратор → конфигурация → выгрузить конфигурацию в файлы → <ИмяРепозиторияФинальногоЗадания>\src\cf);
2. Закоммитить и отправить во внешний репозиторий.

**Особенности**
- Приступать к выполнению этой задачи нужно после того как закроете все созданные мной issue.
- В публичный внешний репозиторий, нельзя помещать код из типовых конфигураций 1С!

**Comment by cobern1976** [comment]
В сетевое хранилище не посылаются файлы размеров более 100 мБт, значит ли это, что в коммите будет достаточно включить разработанные из фич обработки и итоговый cf ?

**Comment by alehinsasha** [comment]
*.dt и *.cf - это бинарные файлы, а в репо должны быть исходники. Обработки разбирает precommit1C, а конфигурацию: конфигуратор → конфигурация → выгрузить конфигурацию в файлы → <ИмяРепозиторияФинальногоЗадания>\src\cf

**Comment by cobern1976** [comment]
скинул выгруженную конфигурацию
