### ISSUE TITLE
Сообщить данные для получения сертификата финалиста

### ISSUE THREAD

**Issue by alehinsasha** [cobern1976/FinalTask#8]
В комментарии к этому issue напишите ваши:
- Имя Фамилию (в дательном падеже)
- Адрес электронной почты, на которую выслать сертификат

**Comment by cobern1976** [comment]
- Галимуллину Денису
- den_box@inbox.ru

**Comment by alehinsasha** [comment]
если вдруг сертификат не получили - напишите!
